# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72767a5eeff334084bf202dadf8d2d08b9b794e6ce0048500e550c6c71ea0591b33a7872e6e3384c70d14b3aea56cecaf5942cdff69bc9c9113e6b4b62275818

test:
  secret_key_base: c0131f95cce2cfdb9673d702ab679630532a33f61286e408de347f2aa15e01b5242bf23ae72cba64795cdefe1f77f506e164f5b415262857dbebfdddaba3145b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
